-keep class com.dabomstew.pkrandom.** { *; }
-keep class compressors.** { *; }
-keep class cuecompressors.** { *; }
-keep class pptxt.** { *; }
-keep class thenewpoketext.** { *; }
-dontwarn java.awt.**
-dontwarn javax.swing.**
